"""empty message

Revision ID: b99e1e4ae5e1
Revises: 11ad8ee2dd94
Create Date: 2019-06-18 12:54:29.169253

"""

# revision identifiers, used by Alembic.
revision = 'b99e1e4ae5e1'
down_revision = '11ad8ee2dd94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=300), nullable=False))
    op.add_column('user', sa.Column('gender', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('user_id', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
