"""empty message

Revision ID: f24691273ca4
Revises: b99e1e4ae5e1
Create Date: 2019-06-18 13:45:46.250079

"""

# revision identifiers, used by Alembic.
revision = 'f24691273ca4'
down_revision = 'b99e1e4ae5e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=300), nullable=True),
    sa.Column('last_name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('first_name', 'last_name', name='user_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
