"""empty message

Revision ID: f7a81ff8d7f0
Revises: 958a448476e4
Create Date: 2019-06-18 14:42:09.689693

"""

# revision identifiers, used by Alembic.
revision = 'f7a81ff8d7f0'
down_revision = '958a448476e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('movie_id', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
